### ISSUE TITLE
Is there a write access to members of codepals?

### ISSUE THREAD

**Issue by avhirupc** [wce-codepals/Must-Read_Articles#1]
I am trying to raise a PR for some reads on caching . I think the repo admin missed out on giving write access to the members?
@ashtnemi448 Can you help me out?

**Comment by adeepak7** [comment]
@avhirupc Made you owner. Now there should not be any problem.

**Comment by avhirupc** [comment]
@adeepak7 Thanks @adeepak7 . Hopefully, this list of articles groups with time.
